/* These two must align, going to insert at least 25 links and the corresponding votes (fake user votes),
many more votes lines than links lines since a line for each. Linkid is 1 -indexed*/
/*http://stackoverflow.com/questions/14481942/create-unix-timestamp-in-mysql*/
INSERT INTO Links(id, datecreated, category, subcategory, title, link, challenge, description, filter)
VALUES (1, UNIX_TIMESTAMP(NOW()), 'html', 'fundamentals',' Your first HTML/CSS tutorial - Codeacademy', 'https://www.codecademy.com/learn/web', 'beginner', 'Codeacademy gets you coding immediately, and does a great job of breaking complicated concepts into understandable bits.', 'course'),
(2, UNIX_TIMESTAMP(NOW()), 'html', 'fundamentals', 'Simple, comprehensive guide to beginner HTML/CSS concepts', 'http://learn.shayhowe.com/html-css/', 'beginner', 'Great breakdown of fundamental HTML and CSS concepts for beginners, covers all key principles', 'article' ),
(3, UNIX_TIMESTAMP(NOW()), 'html', 'fullsite', 'Learn to build a full site from scratch', 'http://learn.shayhowe.com/advanced-html-css/', 'intermediate', 'You know HTML/CSS, but how to develop a user-friendly website without help? This wil take you step by step.', 'article'),
(4, UNIX_TIMESTAMP(NOW()), 'html', 'fullsite', 'Build a fully interactive site with basic Javascript', 'https://www.codecademy.com/en/skills/make-an-interactive-website', 'intermediate', 'Codeacademy-assisted tutorial for building a site with basic Javascript. Great step after first HTML/CSS lessons.', 'practical'),
(5, UNIX_TIMESTAMP(NOW()), 'html', 'responsive', 'Understand design patterns of responsive design', 'https://teamtreehouse.com/library/responsive-layouts', 'intermediate', 'Video breakdown of what it means to be "responsive", and patterns to consider before delving into CSS', 'video'),
(6, UNIX_TIMESTAMP(NOW()), 'html', 'responsive', 'Build flexbox layouts that fit any screen size','https://teamtreehouse.com/library/css-flexbox-layout', 'advanced', 'Video series on flexbox layouts, a design strategy used with single page apps to avoid hours of CSS wrangling' ,'video'),
(7, UNIX_TIMESTAMP(NOW()), 'html', 'fundamentals', 'Colorful book on HTML/CSS with downloadable examples', 'http://www.amazon.com/HTML-CSS-Design-Build-Websites/dp/1118008189', 'beginner', 'Book with lots of pictures and diagrams on major HTML/CSS principles. Excellent for first-timers.', 'book'),
(8, UNIX_TIMESTAMP(NOW()), 'javascript', 'd3', 'Learn D3 principles then build first chart', 'http://alignedleft.com/tutorials', 'intermediate', 'Full breakdown of D3 principles and then a line by line tutorial on building bar graphs. Good first practical exercise.', 'article'),
(9, UNIX_TIMESTAMP(NOW()), 'javascript', 'd3', 'Build bar chart with line by line explanation', 'http://www.recursion.org/d3-for-mere-mortals/', 'intermediate', 'Brief breakdown of all the D3 pieces needed to build a bar chart. Short but very good depth.','article'),
(10, UNIX_TIMESTAMP(NOW()), 'javascript', 'jquery', 'jQuery will make front-end development a joy', 'https://www.codeschool.com/courses/try-jquery', 'beginner', 'Great resource for your first crack at jQuery. Mix of videos and practical. Get coding immediately!', 'course'),
(11, UNIX_TIMESTAMP(NOW()), 'javascript', 'jquery', 'More advanced jQuery concepts for real-time apps', 'https://www.codeschool.com/courses/jquery-the-return-flight', 'advanced', 'Introduction to asynchronous principles of jQuery. Will require some back-end knowledge, but key for modern web apps', 'course' ),
(12, UNIX_TIMESTAMP(NOW()), 'javascript', 'fundamentals', 'Learn the fundamentals of the javascript language, easy to advanced', 'http://eloquentjavascript.net/', 'intermediate', 'E-book on all the major principles of Javascript. Especially good intro to higher order functions and functional programming.', 'book'),
(13, UNIX_TIMESTAMP(NOW()), 'javascript', 'fundamentals', 'Colorful book on basic Javascript with downloadable examples', 'http://www.amazon.com/JavaScript-JQuery-Interactive-Front-End-Development/dp/1118531647/ref=pd_bxgy_14_2?ie=UTF8&refRID=070FWNNNXJRMGEDTZZPM', 'beginner', 'Book with lots of pictures and diagrams on major Javascript principles. Excellent for first-timers.', 'book'),
(14, UNIX_TIMESTAMP(NOW()), 'javascript', 'fundamentals', 'Interactive intro to Javascript for first-timers', 'https://www.codeschool.com/courses/javascript-road-trip-part-1','beginner', 'Start coding Javascript immediately with no background in this tutorial. Videos then challenges. About 2 hour course.', 'course'),
(15, UNIX_TIMESTAMP(NOW()), 'javascript', 'node', 'Command line-based exercises for Node basics', 'http://nodeschool.io/', 'intermediate', 'This one is great if you know the very basics of Node.js, and if you just want to get started with solving little problems of all levels.', 'practical'),
(16, UNIX_TIMESTAMP(NOW()), 'javascript', 'react', 'Practice with basic concepts of React.js', 'http://buildwithreact.com/tutorial', 'advanced', 'React can be challenging, espcially if it is your first MVC framework. Get quick challenges on a few of the major principles.', 'practical'),
(17, UNIX_TIMESTAMP(NOW()), 'databases', 'fundamentals', 'Get started with SQL databases', 'https://www.codecademy.com/learn/learn-sql', 'beginner', 'First steps to mastering SQL. No experience required. Breaks SQL into very understandable chunks.', 'course'),
(18, UNIX_TIMESTAMP(NOW()), 'databases', 'analytics', 'Create valuable business analytics with SQL knowledge', 'https://www.codecademy.com/learn/sql-analyzing-business-metrics', 'intermediate', 'Hands on experience with basic business analyitcs with SQL. Get coding immediately.', 'practical'),
(19, UNIX_TIMESTAMP(NOW()), 'databases', 'fundamentals', 'Videos and quick challenges for learning SQL', 'https://www.codeschool.com/courses/try-sql', 'beginner', 'Video explanations of SQL fundamentals followed by challenges. Great for first time with SQL.', 'course'),
(20, UNIX_TIMESTAMP(NOW()), 'databases', 'fundamentals', 'Video series on SQL basics', 'https://www.udemy.com/sql-database-for-beginners/', 'beginner', 'Video-oriented course on learning SQL, for first-timers', 'course'),
(21, UNIX_TIMESTAMP(NOW()), 'databases', 'dbmgmt', 'Design databases that scale with your product', 'https://www.udemy.com/database-design/', 'beginner', 'Learn the process behind developing any type of scalable database. Language agnostic. Make sure your database is as useful as possible', 'course'),
(22, UNIX_TIMESTAMP(NOW()), 'databases', 'analytics', 'Create SQL insights for more profit', 'https://teamtreehouse.com/library/reporting-with-sql', 'intermediate', 'Learn common reporting principles, and how to format your analytics so that they are understandable and universally actionable', 'video'),
(23, UNIX_TIMESTAMP(NOW()), 'databases', 'fundamentals', 'Learn the basics of MongoDB for MEAN stack', 'https://teamtreehouse.com/library/mongo-basics', 'beginner', 'Course for learning the basics of MongoDB. This is a great technology for staring a database when the structure will be unclear.', 'course'),
(24, UNIX_TIMESTAMP(NOW()), 'databases', 'dbmgmt', 'Database management principles with helpful diagrams', 'http://code.tutsplus.com/tutorials/relational-databases-for-dummies--net-30244', 'beginner', 'What is a relational database? What is the difference between SQL and NoSQL? This will give some guidance on which database to go with', 'article'), 
(25, UNIX_TIMESTAMP(NOW()), 'html', 'fullsite', 'Build a couple typical websites with guidance', 'https://dash.generalassemb.ly/projects', 'beginner', 'Dash is a coding tutorial by General Assembly that allows you to start coding typical sites with help, like personal or small business.', 'practical'),
(26, UNIX_TIMESTAMP(NOW()), 'javascript', 'node', 'Build your first node app with this guide', 'http://www.nodebeginner.org/', 'intermediate', 'This e-book will give yo a step by step guide to write your first Node.js app. Some JS experience needed.', 'book'),
(27, UNIX_TIMESTAMP(NOW()), 'javascript', 'node', 'Great book to explain Node basics', 'https://leanpub.com/mean-machine', 'intermediate', 'No idea where to get started with Node? This is perfect for you. Explains the basics and then gets you building a full MEAN app.', 'book'),
(28, UNIX_TIMESTAMP(NOW()), 'javascript', 'node', 'Videos and exercises on Node basics', 'https://www.codeschool.com/courses/real-time-web-with-node-js', 'intermediate', 'Course on Node basics. May be a little fast-paced if this is your very first time. But very thorough.', 'course'),
(29, UNIX_TIMESTAMP(NOW()), 'html', 'fullsite', 'CSS positioning is hard. Here is a guide.', 'http://learnlayout.com/', 'beginner', 'CSS positioning can seem pretty foreign when you first learn it. This guide will explain and make your layouts much easier.', 'article'),
(30, UNIX_TIMESTAMP(NOW()), 'html', 'responsive', 'Learn the flexbox system for modern design', 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/', 'advanced', 'Flexbox design has some different rules than typical CSS layouts. This article explores the new system', 'article'),
(31, UNIX_TIMESTAMP(NOW()), 'databases', 'fundamentals', 'Get started with MongoDB', 'https://www.codeschool.com/courses/the-magical-marvels-of-mongodb', 'beginner', 'CodeSchool class on the basics of MongoDB. May be helpful to have some knowledge of databases before this', 'course'),
(32, UNIX_TIMESTAMP(NOW()), 'html', 'responsive', 'The flexbox layout for those experienced with CSS', 'https://teamtreehouse.com/library/build-a-responsive-navigation-with-flexbox', 'advanced', 'Video for those with CSS understanding on how to organize your site around flexbox layouts', 'video'),
(33, UNIX_TIMESTAMP(NOW()), 'javascript', 'node', 'Learn to use Grunt to make development easier', 'https://teamtreehouse.com/library/up-and-running-with-grunt', 'intermediate', 'Grunt or another taskrunner is a crucial part of a Node dev eneviornent. Need some Node expereience before integrating', 'video'), 
(34, UNIX_TIMESTAMP(NOW()), 'javascript', 'react', "Idiot's guide to starting with React", 'http://tylermcginnis.com/reactjs-tutorial-a-comprehensive-guide-to-building-apps-with-react/', 'intermediate', 'React is great for real-time web apps, but it can be a little out there if you have never done an MVS framework before. This breaks it down.', 'article'),
(35, UNIX_TIMESTAMP(NOW()), 'javascript', 'fundamentals', 'Javascript so easy a cat could do it!', 'http://jsforcats.com/', 'beginner', 'Learn the basics of the language, dev tools and everything else you need to become a Javascript developer', 'article'),
(36, UNIX_TIMESTAMP(NOW()), 'html', 'fullsite', 'Another guide to always challenging CSS positioning', 'https://scotch.io/bar-talk/5-things-you-might-not-know-about-the-css-positioning-types', 'beginner', 'So you started learning CSS, but the positioning concept has your mind in a pretzel? This one will get into the nitty gritty so you can fully get it.', 'article'),
(37, UNIX_TIMESTAMP(NOW()), 'html', 'responsive', 'Flexbox breakdown with pretty diagrams', 'https://scotch.io/tutorials/a-visual-guide-to-css3-flexbox-properties', 'advanced', 'Flexbox got you down? No worries. Another set of diagrams to help explain this fully and dig deep into the wonders of CSS.', 'article'),
(38, UNIX_TIMESTAMP(NOW()), 'databases', 'fundamentals', 'Small SQL challenges for beginners', 'http://sqlbolt.com/', 'beginner', 'Learn SQL by doing! Short challenges to get you coding and familiar immediately. Great for first-timers', 'practical'),
(39, UNIX_TIMESTAMP(NOW()), 'databases', 'fundamentals', 'Book takes you from SQL novice to intermediate', 'http://www.amazon.com/SQL-Minutes-Sams-Teach-Yourself/dp/0672336073/ref=sr_1_1?s=books&ie=UTF8&qid=1456952055&sr=1-1&keywords=sql+in+10+minutes', 'beginner', 'Popular SQL book to nail down all the basics and move right into intermediate with series of short challenges.' ,'book');

INSERT INTO Votes(linkid, timeVoted, voteNumber)
VALUES (1, UNIX_TIMESTAMP(NOW()), 1),
(1, UNIX_TIMESTAMP(NOW()), 2),
(1, UNIX_TIMESTAMP(NOW()), 3),
(1, UNIX_TIMESTAMP(NOW()), 4),
(1, UNIX_TIMESTAMP(NOW()), 5),
(1, UNIX_TIMESTAMP(NOW()), 6),
(1, UNIX_TIMESTAMP(NOW()), 7),
(1, UNIX_TIMESTAMP(NOW()), 8),
(2, UNIX_TIMESTAMP(NOW()), 1),
(2, UNIX_TIMESTAMP(NOW()), 2),
(2, UNIX_TIMESTAMP(NOW()), 3),
(2, UNIX_TIMESTAMP(NOW()), 4),
(2, UNIX_TIMESTAMP(NOW()), 5),
(2, UNIX_TIMESTAMP(NOW()), 6),
(2, UNIX_TIMESTAMP(NOW()), 7),
(3, UNIX_TIMESTAMP(NOW()), 1),
(4, UNIX_TIMESTAMP(NOW()), 1),
(4, UNIX_TIMESTAMP(NOW()), 2),
(4, UNIX_TIMESTAMP(NOW()), 3),
(4, UNIX_TIMESTAMP(NOW()), 4),
(4, UNIX_TIMESTAMP(NOW()), 5),
(4, UNIX_TIMESTAMP(NOW()), 6),
(4, UNIX_TIMESTAMP(NOW()), 7),
(4, UNIX_TIMESTAMP(NOW()), 8),
(4, UNIX_TIMESTAMP(NOW()), 9),
(4, UNIX_TIMESTAMP(NOW()), 10),
(4, UNIX_TIMESTAMP(NOW()), 11),
(5, UNIX_TIMESTAMP(NOW()), 1),
(5, UNIX_TIMESTAMP(NOW()), 2),
(5, UNIX_TIMESTAMP(NOW()), 3),
(6, UNIX_TIMESTAMP(NOW()), 1),
(6, UNIX_TIMESTAMP(NOW()), 2),
(6, UNIX_TIMESTAMP(NOW()), 3),
(6, UNIX_TIMESTAMP(NOW()), 4),
(7, UNIX_TIMESTAMP(NOW()), 1),
(7, UNIX_TIMESTAMP(NOW()), 2),
(8, UNIX_TIMESTAMP(NOW()), 1),
(8, UNIX_TIMESTAMP(NOW()), 2),
(8, UNIX_TIMESTAMP(NOW()), 3),
(8, UNIX_TIMESTAMP(NOW()), 4),
(9, UNIX_TIMESTAMP(NOW()), 1),
(9, UNIX_TIMESTAMP(NOW()), 2),
(9, UNIX_TIMESTAMP(NOW()), 3),
(10, UNIX_TIMESTAMP(NOW()), 1),
(10, UNIX_TIMESTAMP(NOW()), 2),
(10, UNIX_TIMESTAMP(NOW()), 3),
(10, UNIX_TIMESTAMP(NOW()), 4),
(10, UNIX_TIMESTAMP(NOW()), 5),
(11, UNIX_TIMESTAMP(NOW()), 1),
(11, UNIX_TIMESTAMP(NOW()), 2),
(12, UNIX_TIMESTAMP(NOW()), 1),
(13, UNIX_TIMESTAMP(NOW()), 1),
(13, UNIX_TIMESTAMP(NOW()), 2),
(13, UNIX_TIMESTAMP(NOW()), 3),
(13, UNIX_TIMESTAMP(NOW()), 4),
(13, UNIX_TIMESTAMP(NOW()), 5),
(13, UNIX_TIMESTAMP(NOW()), 6),
(13, UNIX_TIMESTAMP(NOW()), 7),
(13, UNIX_TIMESTAMP(NOW()), 8),
(13, UNIX_TIMESTAMP(NOW()), 9),
(13, UNIX_TIMESTAMP(NOW()), 10),
(13, UNIX_TIMESTAMP(NOW()), 11),
(13, UNIX_TIMESTAMP(NOW()), 12),
(13, UNIX_TIMESTAMP(NOW()), 13),
(14, UNIX_TIMESTAMP(NOW()), 1),
(14, UNIX_TIMESTAMP(NOW()), 2),
(14, UNIX_TIMESTAMP(NOW()), 3),
(14, UNIX_TIMESTAMP(NOW()), 4),
(15, UNIX_TIMESTAMP(NOW()), 1),
(15, UNIX_TIMESTAMP(NOW()), 2),
(16, UNIX_TIMESTAMP(NOW()), 1),
(16, UNIX_TIMESTAMP(NOW()), 2),
(16, UNIX_TIMESTAMP(NOW()), 3),
(16, UNIX_TIMESTAMP(NOW()), 4),
(17, UNIX_TIMESTAMP(NOW()), 1),
(17, UNIX_TIMESTAMP(NOW()), 2),
(17, UNIX_TIMESTAMP(NOW()), 3),
(17, UNIX_TIMESTAMP(NOW()), 4),
(17, UNIX_TIMESTAMP(NOW()), 5),
(18, UNIX_TIMESTAMP(NOW()), 1),
(18, UNIX_TIMESTAMP(NOW()), 2),
(19, UNIX_TIMESTAMP(NOW()), 1),
(19, UNIX_TIMESTAMP(NOW()), 2),
(19, UNIX_TIMESTAMP(NOW()), 3),
(19, UNIX_TIMESTAMP(NOW()), 4),
(19, UNIX_TIMESTAMP(NOW()), 5),
(19, UNIX_TIMESTAMP(NOW()), 6),
(19, UNIX_TIMESTAMP(NOW()), 7),
(19, UNIX_TIMESTAMP(NOW()), 8),
(19, UNIX_TIMESTAMP(NOW()), 9),
(19, UNIX_TIMESTAMP(NOW()), 10),
(19, UNIX_TIMESTAMP(NOW()), 11),
(19, UNIX_TIMESTAMP(NOW()), 12),
(20, UNIX_TIMESTAMP(NOW()), 1),
(20, UNIX_TIMESTAMP(NOW()), 2),
(20, UNIX_TIMESTAMP(NOW()), 3),
(20, UNIX_TIMESTAMP(NOW()), 4),
(21, UNIX_TIMESTAMP(NOW()), 1),
(22, UNIX_TIMESTAMP(NOW()), 2),
(23, UNIX_TIMESTAMP(NOW()), 1),
(24, UNIX_TIMESTAMP(NOW()), 1),
(24, UNIX_TIMESTAMP(NOW()), 2),
(24, UNIX_TIMESTAMP(NOW()), 3),
(24, UNIX_TIMESTAMP(NOW()), 4),
(24, UNIX_TIMESTAMP(NOW()), 5),
(25, UNIX_TIMESTAMP(NOW()), 1),
(25, UNIX_TIMESTAMP(NOW()), 2),
(25, UNIX_TIMESTAMP(NOW()), 3),
(25, UNIX_TIMESTAMP(NOW()), 4),
(26, UNIX_TIMESTAMP(NOW()), 1),
(26, UNIX_TIMESTAMP(NOW()), 2),
(26, UNIX_TIMESTAMP(NOW()), 3),
(26, UNIX_TIMESTAMP(NOW()), 4),
(26, UNIX_TIMESTAMP(NOW()), 5),
(27, UNIX_TIMESTAMP(NOW()), 1),
(28, UNIX_TIMESTAMP(NOW()), 1),
(28, UNIX_TIMESTAMP(NOW()), 2),
(28, UNIX_TIMESTAMP(NOW()), 3),
(28, UNIX_TIMESTAMP(NOW()), 4),
(29, UNIX_TIMESTAMP(NOW()), 1),
(30, UNIX_TIMESTAMP(NOW()), 1),
(30, UNIX_TIMESTAMP(NOW()), 2),
(30, UNIX_TIMESTAMP(NOW()), 3),
(30, UNIX_TIMESTAMP(NOW()), 4),
(30, UNIX_TIMESTAMP(NOW()), 5),
(30, UNIX_TIMESTAMP(NOW()), 6),
(30, UNIX_TIMESTAMP(NOW()), 7),
(30, UNIX_TIMESTAMP(NOW()), 8),
(30, UNIX_TIMESTAMP(NOW()), 9),
(30, UNIX_TIMESTAMP(NOW()), 10),
(31, UNIX_TIMESTAMP(NOW()), 1),
(31, UNIX_TIMESTAMP(NOW()), 2),
(31, UNIX_TIMESTAMP(NOW()), 3),
(31, UNIX_TIMESTAMP(NOW()), 4),
(31, UNIX_TIMESTAMP(NOW()), 5),
(31, UNIX_TIMESTAMP(NOW()), 6),
(32, UNIX_TIMESTAMP(NOW()), 1),
(32, UNIX_TIMESTAMP(NOW()), 2),
(32, UNIX_TIMESTAMP(NOW()), 3),
(33, UNIX_TIMESTAMP(NOW()), 1),
(33, UNIX_TIMESTAMP(NOW()), 2),
(33, UNIX_TIMESTAMP(NOW()), 3),
(33, UNIX_TIMESTAMP(NOW()), 4),
(34, UNIX_TIMESTAMP(NOW()), 1),
(35, UNIX_TIMESTAMP(NOW()), 1),
(35, UNIX_TIMESTAMP(NOW()), 2),
(36, UNIX_TIMESTAMP(NOW()), 1),
(36, UNIX_TIMESTAMP(NOW()), 2),
(36, UNIX_TIMESTAMP(NOW()), 3),
(36, UNIX_TIMESTAMP(NOW()), 4),
(37, UNIX_TIMESTAMP(NOW()), 1),
(37, UNIX_TIMESTAMP(NOW()), 2),
(37, UNIX_TIMESTAMP(NOW()), 3),
(37, UNIX_TIMESTAMP(NOW()), 4),
(37, UNIX_TIMESTAMP(NOW()), 5),
(37, UNIX_TIMESTAMP(NOW()), 6),
(37, UNIX_TIMESTAMP(NOW()), 7),
(37, UNIX_TIMESTAMP(NOW()), 8),
(37, UNIX_TIMESTAMP(NOW()), 9),
(38, UNIX_TIMESTAMP(NOW()), 1),
(38, UNIX_TIMESTAMP(NOW()), 2),
(38, UNIX_TIMESTAMP(NOW()), 3),
(39, UNIX_TIMESTAMP(NOW()), 1),
(39, UNIX_TIMESTAMP(NOW()), 2),
(39, UNIX_TIMESTAMP(NOW()), 3);